baseURL = '/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[permalinks]
  category = "/:title/"



[menu]
  [[menu.main]]
    pageRef="/"
    name = 'Home'
    url = '/'
    weight = 10
  [[menu.main]]
    pageRef="/category/amphibian/"  
    name = 'Amphibians'
    url = '/category/amphibian/'
    weight = 20
      [[menu.main]]
        pageRef="/category/amphibian/soft/"  
        name = "Soft"
        url = "/category/amphibian/soft/"
        weight = 25
        parent = "Amphibians"
      [[menu.main]]
        pageRef="/category/amphibian/hard/"  
        name = "Hard"
        url = "/category/amphibian/hard/"
        weight = 30
        parent = "Amphibians"
  [[menu.main]]
    pageRef="/category/frogs/"  
    name = 'Frogs'
    url = "/category/frogs/"
    weight = 30
      [[menu.main]]
        pageRef="/category/frogs/green/"  
        name = "Green"
        url = "/category/frogs/green/"
        weight = 10
        parent = "Frogs"
      [[menu.main]]
        pageRef="/category/frogs/orange/"  
        name = "Orange"
        url = "/category/frogs/orange/"
        weight = 20
        parent = "Frogs"
  [[menu.main]]
    pageRef="/category/insects/"  
    name = "Insects"
    url = "/category/insects/"
    weight = 40
      [[menu.main]]
        pageRef="/category/insects/long/"  
        name = "Long"
        url = "/category/insects/long/"
        weight = 10
        parent = "Insects"
      [[menu.main]]
        pageRef="/category/insects/short/"  
        name = "Short"
        url = "/category/insects/short/"
        weight = 20
        parent = "Insects"


